### ISSUE TITLE
check mcpc 1.18 works

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-chunk#157]
https://github.com/PrismarineJS/mineflayer/pull/2339 we're seeing some signs of issues there (see the ci)

**Comment by rom1504** [comment]
<https://github.com/PrismarineJS/mineflayer/runs/4733023434?check_suite_focus=true>

**Comment by rom1504** [comment]
steps to fix
1. load a chunk (there are some there https://github.com/PrismarineJS/prismarine-chunk/tree/master/test/1.18)
2. check what it contains
3. if it looks bad, report

**Comment by ArticSeths** [comment]
When the test start in 1.18, the flat world start in position "y" to -60, the exampleBlockFinder teleport finder bot to 50.5, 4.0, 0.5, but in this positions are air, this is why finds 0 blocks of dirt and fail

**Comment by rom1504** [comment]
It's meant to fall down
Does this happen only for 1.18 ? Is 1.17 different?

**Comment by ArticSeths** [comment]
only in 1.18 because in this update mojang aumented the size of chunks up and down
![1 18](https://user-images.githubusercontent.com/16854230/148825659-68f77514-2ff6-4de5-a943-6cdfa01591ef.png)
![1 17](https://user-images.githubusercontent.com/16854230/148825662-c3f81c83-d7f0-41c5-a6d4-b796d7375c94.png)

**Comment by rom1504** [comment]
Interesting, maybe we should wait longer for the bot to fall
Or change the spawning position
