### ISSUE TITLE
fix offset bug in 1.9 detected by node 10

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-chunk#40]
If you run the test in node 10 you get : 
```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 6652. Received 6654
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readUInt32BE (internal/buffer.js:198:5)
    at Chunk.eatPackedBlockLongs (src/pc/1.9/chunk.js:414:40)
    at Chunk.unpackChunkData (src/pc/1.9/chunk.js:354:31)
    at Chunk.load (src/pc/1.9/chunk.js:325:29)
    at Context.<anonymous> (test/test.js:78:14)
```

I don't really understand the 1.9 implementation. If someone that does (@allain @Flynnn) could have a look, it would be appreciated.

I bet it means that sometimes things don't fully work.

**Comment by Flynnn** [comment]
@rom1504  Howdy, sure, happy to take a look. I'm a bit out of the loop, though, as it's been a while. This has to do with the code I wrote a while ago to deal with the new long packing, yeah? Has the protocol changed with Minecraft and needs to be updated again, or is my code just acting up?

I'll see if I can run the test in node 10 in the next few days. Bit rusty, though, what's the general procedure? I'll figure it out, but if you know off the top of your head that would save me tons of time!

Thank you,

-- Georges

**Comment by Flynnn** [comment]
Yeah, looking a bit closer, it looks like I was aware of this behavior. Node 8 had an extra argument on readUInt32BE called "NoAssert" which I have set to true in my code. I guess Node 10 removed the feature, and whoever has been maintaining my code removed the argument. I don't think offset is being set incorrectly -- rather, Minecraft sends block data in components that are typically around 5 bits but may be as large as 16 bits.

This results in all kind of bizarre offset complications, so my approach was just to load a 32 bit section *around* the block being loaded and then extract the specific block data from there. If the block being read was close to the end of the buffer, then this would result in the 32 bit section going past the buffer's end and readUInt32BE just padding with zeroes, which was fine, because after extraction was done, none of that data was ever used to begin with.

The solution here is either just to extend the buffer by 32 bits, or see if readUInt32BE has any comparable features in Node 10. I'll see.

**Comment by rom1504** [comment]
Ah indeed, it seems that noAssert option was removed from readUInt32BE in node10 https://nodejs.org/api/buffer.html#buffer_buf_readuint32be_offset
I guess they thought it was insecure.

**Comment by Flynnn** [comment]
The hilarity is that I've come across some non-official node 10 docs that still list readUInt32BE with the NoAssert argument:

http://www.chiark.greenend.org.uk/doc/nodejs/api/buffer.html#buffer_buf_readint32le_offset_noassert

Do you think it might still be in there, but just not documented?

I'll try to make a commit some time in the next few days fixing the problem in one of the two ways I mentioned.

**Comment by rom1504** [comment]
No, they explicitely say they removed it in the "history" part in https://nodejs.org/api/buffer.html#buffer_buf_readuint32be_offset

**Comment by Flynnn** [comment]
Oh, what do you know! I wish I had spotted that little history dropdown. Thanks for pointing that out.

**Comment by rom1504** [comment]
Does that looks ok to you @Flynnn https://github.com/PrismarineJS/prismarine-chunk/pull/41/files ?

**Comment by Flynnn** [comment]
Yeah, that looks absolutely perfect! Let me know whether it works!

**Comment by rom1504** [comment]
Yes it does fix the issue with node 10. Let's merge it.
Thanks for the help @Flynnn !

**Comment by Flynnn** [comment]
No prob! This stuff gets directed to my email, so if you ever need help again with this (or anything else), you can summon me by @Flynnn -ing me
